### ISSUE TITLE
ExtractOpcodeName

### ISSUE THREAD

**Issue by leo228** [w4kfu/waronline_fun#4]
ok here are the steps I do with pictures don't know if they are the correct way to load them
[](url)https://mega.nz/#!v4R3yRCQ!TN4UsQU4gSsx2BCpzp0whTntd-k8zlnX1yg0QNzGiYA

opcodes that I need with values are
 F_CURRENT_EVENTS // missing
 F_MONSTER_POSITION // missing
 F_ACTION_COUNTER_TIMESTAMP_INFO // missing
 F_VIEW_LOOT_BAG // missing
 F_MARKETING_REWARD_LIST // missing
 F_RRQ //missing
 F_UPDATE_ITEM_COOLDOWN // missing
 F_ADVANCED_WAR_REPORT
 F_WAR_REPORT // missing

**Comment by leo228** [comment]
ok here are the steps I do with pictures don't know if they are the correct way to load them[](url)https://mega.nz/#!v4R3yRCQ!TN4UsQU4gSsx2BCpzp0whTntd-k8zlnX1yg0QNzGiYA

**Comment by w4kfu** [comment]
Hello,

Thanks for all the explanation.
Are you using the script on the correct binary?
This script has been written for a specific version of the binary, the md5 hash is : "DC4F692AAA7A9AEF5EE2D2A3F00C690B".
From where are coming the opode you listed below?

**Comment by leo228** [comment]
hello if you load the war exe into hxd editor then select search then find F_CURRENT_EVENTS  they all show up

**Comment by w4kfu** [comment]
What do you mean by "I try other nothing happens"? 
Can you upload the binary somewhere? I don't have it anymore so I can take a look.

**Comment by leo228** [comment]
what is the binary ? here is a link to all files I used https://mega.nz/#F!u5R1WABD!7GXPDzcoTi_YhUlY03hUxQ

**Comment by w4kfu** [comment]
This script has been written for the binary "war.exe" with md5 hash equal to : "DC4F692AAA7A9AEF5EE2D2A3F00C690B"
 
If I compute the md5 of war.exe from your archive, I have:

```
$ md5sum.exe WAR.exe
3c78a494df37f707ab013360ba4cfbf6 *WAR.exe
```

I will update the script when I have time and get back to you

**Comment by leo228** [comment]
ok thanks m8 for taking time to help :)

**Comment by w4kfu** [comment]
Script has been updated with your version of the binary : https://github.com/w4kfu/waronline_fun/commit/a49ae3d051aeba0743d1df4417aacfe52bcc9f16.

Could you test it?

Also it seems that not all the opcode string name are present in the binary, only some (~61).

**Comment by leo228** [comment]
I get this error when loading the script
https://mega.nz/#!ih52WA7Z!RYux4EB7VcsUUWPoXmEMXtrvS4VptkWWBs0cLlrPZrY

**Comment by w4kfu** [comment]
Simple import error, could be fixed by yourself...
anyway : https://github.com/w4kfu/waronline_fun/commit/9d4a4d8bca0054f056c5b4d4d1ddea2eee640539

**Comment by leo228** [comment]
ok I tied it but nothing happens when I load the script could you do it at your end and post the list?

**Comment by w4kfu** [comment]
```
[+]   8 (0x08) ; F_OBJECT_STATE
[+]  13 (0x0D) ; F_CURRENT_EVENTS
[+]  18 (0x12) ; F_REQUEST_CHAR_TEMPLATES
[+]  26 (0x1A) ; F_MONSTER_POSITION
[+]  28 (0x1C) ; F_GUILD_DATA
[+]  31 (0x1F) ; F_PET_INFO
[+]  40 (0x28) ; F_SHOW_DIALOG
[+]  42 (0x2A) ; F_QUEST_INFO
[+]  56 (0x38) ; F_PLAYER_EXPERIENCE
[+]  64 (0x40) ; F_ACTION_COUNTER_TIMESTAMP_INFO
[+]  69 (0x45) ; F_PLAYER_STATS
[+]  70 (0x46) ; F_MONSTER_STATS
[+]  77 (0x4D) ; F_PLAYER_RENOWN
[+]  79 (0x4F) ; F_PLAYER_LEVEL_UP
[+]  95 (0x5F) ; F_VIEW_LOOT_BAG
[+]  96 (0x60) ; F_PLAY_SOUND
[+] 100 (0x64) ; F_MARKETING_REWARD_LIST
[+] 110 (0x6E) ; F_LOCALIZED_STRING
[+] 113 (0x71) ; F_CREATE_MONSTER
[+] 115 (0x73) ; F_RRQ
[+] 133 (0x85) ; F_MAIL
[+] 139 (0x8B) ; F_MORALE_LIST
[+] 140 (0x8C) ; F_SURVEY_ADDQUESTION
[+] 146 (0x92) ; F_GFX_MOD
[+] 147 (0x93) ; F_INSTANCE_INFO
[+] 153 (0x99) ; F_HELP_DATA
[+] 154 (0x9A) ; F_UPDATE_LASTNAME
[+] 157 (0x9D) ; F_GET_CULTIVATION_INFO
[+] 166 (0xA6) ; F_SIEGE_WEAPON_RESULTS
[+] 168 (0xA8) ; F_UPDATE_HOT_SPOT
[+] 169 (0xA9) ; F_GET_ITEM
[+] 172 (0xAC) ; F_INTRO_CINEMA
[+] 181 (0xB5) ; F_SOCIAL_NETWORK
[+] 184 (0xB8) ; F_UPDATE_ITEM_COOLDOWN
[+] 188 (0xBC) ; F_PLAYER_INVENTORY
[+] 189 (0xBD) ; F_CHARACTER_INFO
[+] 190 (0xBE) ; F_INIT_STORE
[+] 191 (0xBF) ; F_STORE_BUY_BACK
[+] 192 (0xC0) ; F_OBJECTIVE_INFO
[+] 193 (0xC1) ; F_OBJECTIVE_UPDATE
[+] 200 (0xC8) ; F_SCENARIO_PLAYER_INFO
[+] 201 (0xC9) ; F_FLAG_OBJECT_STATE
[+] 207 (0xCF) ; F_PUNKBUSTER
[+] 208 (0xD0) ; F_ITEM_SET_DATA
[+] 215 (0xD7) ; F_GROUP_STATUS
[+] 218 (0xDA) ; F_INFLUENCE_DETAILS
[+] 221 (0xDD) ; F_OBJECT_EFFECT_STATE
[+] 225 (0xE1) ; F_EXPERIENCE_TABLE
[+] 226 (0xE2) ; F_CREATE_PLAYER
[+] 227 (0xE3) ; F_UPDATE_STATE
[+] 232 (0xE8) ; F_INTERACT_RESPONSE
[+] 233 (0xE9) ; F_QUEST_LIST
[+] 234 (0xEA) ; F_QUEST_UPDATE
[+] 236 (0xEC) ; F_QUEST_LIST_UPDATE
[+] 237 (0xED) ; F_CAREER_CATEGORY
[+] 242 (0xF2) ; F_CAREER_PACKAGE_INFO
[+] 245 (0xF5) ; F_CHANNEL_LIST
[+] 246 (0xF6) ; F_TACTICS
[+] 247 (0xF7) ; F_TOK_ENTRY_UPDATE
[+] 250 (0xFA) ; F_INFLUENCE_UPDATE
[+] 251 (0xFB) ; F_INFLUENCE_INFO
```

**Comment by w4kfu** [comment]
It seems that the user @leo228 removed all his comment...
Closing the issue.
